spring:
  # Application Name
  application:
    name: UserService

  # Currently Activated Profile
  profiles:
    active: dev

  # Devtools Auto Reload
  devtools:
    restart:
      enabled: true